import { CONTACT } from '../content/site'

export type LegalKind = 'privacy' | 'terms'

interface Section {
  h: string
  p: string[]
}

const PRIVACY: Section[] = [
  {
    h: 'What we store',
    p: [
      'When you submit a forecast, we store the job metadata (company, your query text, timestamps, status) and the generated report in our database. Your account identity comes from your login provider (email address).',
      'If you self-host ForecastGPT, all of this lives in your own database and never leaves your infrastructure.',
    ],
  },
  {
    h: 'Documents we fetch',
    p: [
      'Reports are generated from public filings — quarterly results decks, fact sheets and earnings-call transcripts discovered via screener.in and exchange/issuer websites (NSE, BSE, company IR pages). Downloaded copies are cached on the server to avoid re-downloading the same document.',
      'Live share prices are fetched from public market-data endpoints.',
    ],
  },
  {
    h: 'Your own provider key (BYOK)',
    p: [
      'If you paste your own LLM provider key, it is held in your browser and passed with your request only. It is used once for that job and is never written to the database or logs.',
    ],
  },
  {
    h: 'What we do NOT do',
    p: [
      'No advertising, no analytics/tracking cookies, no selling of data. The console stores your session and preferences (API key, provider key) in your browser’s localStorage — clear your browser data and it is gone.',
    ],
  },
  {
    h: 'AI-generated content',
    p: [
      'Reports are generated by AI models from public documents. They can be incomplete or wrong — verify anything material against the cited filings. Nothing here is investment advice.',
    ],
  },
]

const TERMS: Section[] = [
  {
    h: 'Acceptance',
    p: [
      'By using ForecastGPT you agree to these terms. If you self-host the software, the MIT license governs the code; these terms apply to the hosted experience.',
    ],
  },
  {
    h: 'Not investment advice',
    p: [
      'ForecastGPT produces AI-generated narrative outlooks from public filings for informational purposes only. It is not a recommendation, solicitation, or investment advice. Markets involve risk; do your own research and consult a licensed advisor before making decisions.',
    ],
  },
  {
    h: 'Accuracy & availability',
    p: [
      'Reports depend on third-party public sources (screener.in, NSE/BSE filings, market-data endpoints) which can change or disappear. The service is provided “as is”, without warranties of any kind, and may be slow, rate-limited, or unavailable.',
    ],
  },
  {
    h: 'Fair use',
    p: [
      'Free usage is quota-limited per person. Automated abuse, attempts to reach internal systems, or bypassing limits beyond the intended BYOK mechanism may result in blocked keys or accounts.',
    ],
  },
  {
    h: 'Contact',
    p: [`Questions about these terms: ${CONTACT.email} or GitHub (${CONTACT.github}).`],
  },
]

export default function LegalPage({ kind }: { kind: 'privacy' | 'terms' }) {
  const sections = kind === 'privacy' ? PRIVACY : TERMS
  return (
    <div className="page-narrow">
      <h1 className="page-title">{kind === 'privacy' ? 'Privacy Policy' : 'Terms of Use'}</h1>
      <p className="faint small">Last updated: February 2026 · ForecastGPT</p>
      {sections.map((s) => (
        <section key={s.h} style={{ marginTop: 22 }}>
          <h2 className="page-section">{s.h}</h2>
          {s.p.map((para, i) => (
            <p className="muted" key={i} style={{ marginBottom: 8 }}>
              {para}
            </p>
          ))}
        </section>
      ))}
      <p className="muted small" style={{ marginTop: 26 }}>
        Questions? Write to <a href={`mailto:${CONTACT.email}`}>{CONTACT.email}</a>.
      </p>
    </div>
  )
}
